[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "seistoolkit"
version = "0.1.0"
description = "Geophysical processing toolkit"
authors = [
    {name = "Denis Baidikov"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []


[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]
